"""
🛠️ Utilities Package — Các tiện ích dùng chung
"""

from .json_parser import safe_parse_json
from .ai_extractor import (
    get_api_config,
    save_api_config,
    extract_text_from_file,
    extract_vocabulary_with_ai,
    extract_vocabulary_long_text,
    chat_with_ai,
    query_anki_context,
    init_import_history,
    add_to_import_history,
    get_import_history,
    get_import_history_items,
    search_import_history,
    get_history_summary_text,
)
from .deck_cache import (
    get_existing_vocab_from_deck,
    invalidate_deck_cache,
)
from .prompt_config import (
    get_system_prompt,
    get_json_template,
    get_fields,
    get_field_count,
    get_effective_config,
    get_signature,
    save_config as save_prompt_config,
    reset_config as reset_prompt_config,
    validate_json_template,
    has_overrides,
    get_field_map,
    apply_field_map_to_cfg,
    auto_field_name,
    get_card_show,
)
from .batch_processor import (
    parse_word_list,
    smart_group_words,
    process_large_word_list,
    organize_decks_with_ai,
    create_decks_from_organization,
    estimate_batch_cost,
)
from .deck_manager import (
    get_deck_tree,
    create_deck,
    rename_deck,
    delete_deck,
    get_deck_card_count,
    refresh_anki,
)

__all__ = [
    "safe_parse_json",
    "get_api_config",
    "save_api_config",
    "extract_text_from_file",
    "extract_vocabulary_with_ai",
    "extract_vocabulary_long_text",
    "chat_with_ai",
    "query_anki_context",
    "init_import_history",
    "add_to_import_history",
    "get_import_history",
    "get_import_history_items",
    "search_import_history",
    "get_history_summary_text",
    "get_system_prompt",
    "get_json_template",
    "get_fields",
    "get_field_count",
    "get_effective_config",
    "get_signature",
    "save_prompt_config",
    "reset_prompt_config",
    "validate_json_template",
    "has_overrides",
    "get_field_map",
    "apply_field_map_to_cfg",
    "auto_field_name",
    "get_card_show",
    "parse_word_list",
    "smart_group_words",
    "process_large_word_list",
    "organize_decks_with_ai",
    "create_decks_from_organization",
    "estimate_batch_cost",
    "get_deck_tree",
    "create_deck",
    "rename_deck",
    "delete_deck",
    "get_deck_card_count",
    "refresh_anki",
]
